# Generated by Django 5.1.4 on 2024-12-11 09:04

import account.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, validators=[account.models.MinAgeValidator(18)], verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, upload_to='static/images/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, choices=[('Gujarat', 'Gujarat'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu'), ('Delhi', 'Delhi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
