# Generated by Django 5.1.4 on 2024-12-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
