# Generated by Django 5.1.4 on 2024-12-13 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_delete_artists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('auction_date_time', models.DateTimeField()),
                ('auction_min_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=255)),
                ('framing', models.BooleanField(default=False)),
                ('theme', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=200)),
                ('authenticity', models.CharField(max_length=200)),
                ('narrative', models.TextField()),
                ('guidelines', models.TextField()),
                ('artist_style', models.TextField()),
                ('notable_work', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.category')),
            ],
        ),
    ]
