# Generated by Django 5.1.4 on 2024-12-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_bid_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('process', 'Process'), ('win', 'Win')], default='process', max_length=20),
        ),
    ]
